Dvd/dvd/config/routes.rb
Dvd::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/profile' => 'users#show'

  devise_scope :user do
    authenticated :user do
      root :to => 'quizzes#index', as: :authenticated_root
    end

      
  end  

  resources :quizzes  do
    resources :questions 
    resources :questions_quizzes, only: :update
  end

  resources :questions do
    resources :answers
  end

  get '/a-propos' => 'high_voltage/pages#show', id: 'about', as: :about

  root to: 'high_voltage/pages#show', id: 'home'

  post '/quizzes/:id/send_score' =>  'score#send_score', as: :send_score
  get '/quizzes/:id/score' => 'score#show', as: :score

end

Dvd/dvd/app/models/question.rb
class Question < ActiveRecord::Base
	has_many :questions_quizzes
	has_many :quizzes, :through => :questions_quizzes
	has_many :answers, :dependent => :destroy
	accepts_nested_attributes_for :answers, :reject_if => :all_blank, :allow_destroy => true

	has_many :proposals, through: :questions_quizzes


	#acts_as_taggable # Alias for acts_as_taggable_on :tags
	acts_as_taggable_on :theme
	acts_as_taggable_on :level
	scope :by_join_date, order("created_at DESC")


	serialize :themes
	serialize :levels

	scope :by_question, ->(question){ where(question_id: question.id) }
	
	def qcm?
	  # return if the question is a qcm (it has proposals), or an open question (it has solutions)
	end

	def next(quiz)

		question_quiz = self.questions_quizzes.by_quiz(quiz).first.try(:next)
		
		if question_quiz.present?
			question_quiz.question
		end

	end

end


# range = 1..5
# store = 0

# range.each_with_index do |value, i|
#   next_value = range.to_a[i+1].nil? ? 0 : range.to_a[i+1]
#   store += value + next_value
# end

# self = Quiz.find(:id)

Dvd/dvd/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_quiz, only: [:show, :update]
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource param_method: :question_params

  # GET /questions
  # GET /questions.json

  def quiz_questions
    @questions = set_quiz.questions
  end

  def index
    @questions = Question.all
  end

  def show
    # passe l'id de la question suivante
    @next_question = @question.next(@quiz)
    @answers = @question.answers
    @proposal = Proposal.new
    @questions_quiz = @quiz.questions_quizzes.where(question: @question).first

    # @question.proposals.create()
  end

  # GET /questions/new
  def new
    @question = Question.new
    @question.answers.build
    @all_themes = get_themes
    @all_levels = get_levels
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.answers.build(params[:question][:answer])

    # Creating associations for themes and levels
    asked_themes = params[:question][:theme_list].reject { |c| c.empty? }
    asked_levels = params[:question][:level_list].reject { |c| c.empty? }
    @question.theme_list.add(asked_themes)
    @question.level_list.add(asked_levels)


    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_path, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: questions_path }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
        format.js { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
        format.js { head :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question)
            .permit(:query, :explanation, answers_attributes:[:id, :title, :true_false, :_destroy])
    end

    def set_quiz
      @quiz = Quiz.find(params[:quiz_id])
    end

    def get_themes
      Question.theme_counts
    end

    def get_levels
      Question.level_counts
    end

end

Dvd/dvd/app/helpers/questions_helper.rb
module QuestionsHelper
	include ActsAsTaggableOn::TagsHelper
end

Dvd/dvd/app/views/questions/_answer_fields.html.erb
<div class="nested-fields">
	<%= f.label :title, "Contenu de la réponse" %>
  <%= f.input :title, label:false %></br>
  <div class="true_false">
  	<%= f.label :true_false, "Vrai", :value => "true"  %>
  	<%= f.radio_button :true_false, true %>
  	<%= f.label :true_false, "Faux", :value => "false" %>
  	<%= f.radio_button :true_false, false, :checked => true %></br>
  	<%= link_to_remove_association "Supprimer la réponse", f %>
  </div>
</div>

Dvd/dvd/app/views/questions/_form.html.erb
<%= simple_form_for @question, defaults: { input_html: { class: 'form-horizontal' } } do |f| %>

  <div class="field">
    <%= f.label :query, "Question"%><br>
    <%= f.text_field :query %>
  </div>
  <div class="field">
    <%= f.label :explanation, "Explication qui accompagne la solution" %><br>
    <%= f.text_field :explanation %>
  </div>

<h2>Réponses</h2>

  <%= f.simple_fields_for :answers  do |answer_builder| %>
    <p>
      <%= render 'answer_fields', :f => answer_builder %>
      <div class="links">
        <%= link_to_add_association 'Ajouter une réponse', f, :answers %>
      </div>
    </p>
  <% end %>

<h2>Thèmes</h2>

<div class="form-group">
    <%= f.label :theme_list, "Catégories" %><br>
    <%= f.collection_check_boxes :theme_list, @all_themes, :name, :name, html_options = {class: "checkbox"} %>
</div>
<div class="form-group">
    <%= f.label :level_list, "Niveau de difficulté" %><br>
    <%= f.collection_check_boxes :level_list, @all_levels, :name, :name, html_options = {class: "checkbox"} %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

Dvd/dvd/app/views/questions/_quiz_form.html.erb
<%= simple_form_for([@quiz, @question]), defaults: { input_html: { class: 'form-horizontal' } } do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :query %><br>
    <%= f.text_field :query %>
  </div>
  <div class="field">
    <%= f.label :explanation %><br>
    <%= f.text_field :explanation %>
  </div>

  <div class="form-group">
      <%= f.label :theme_list, "Catégories" %><br>
      <%= f.collection_check_boxes :theme_list, @all_themes, :name, :name, html_options = {class: "checkbox"} %>
  </div>
  <div class="form-group">
      <%= f.label :level_list, "Niveau de difficulté" %><br>
      <%= f.collection_check_boxes :level_list, @all_levels, :name, :name, html_options = {class: "checkbox"} %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Dvd/dvd/app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

Dvd/dvd/app/views/questions/index.html.erb
<h1>Mon nouveau quiz aura les questions suivantes : </h1>

<table>
  <thead>
    <tr>
      <th>Query</th>
      <th>Explanation</th>
      <th>Level(s)</th>
      <th>Theme(s)</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.query %></td>
        <td><%= question.explanation %></td>
        <td><%= question.level_list %></td>
        <td><%= question.theme_list %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

Dvd/dvd/app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

Dvd/dvd/app/views/questions/quiz_questions.html.erb
<h1>Toutes les questions existantes </h1>

<table>
  <thead>
    <tr>
      <th>Query</th>
      <th>Explanation</th>
      <th>Level(s)</th>
      <th>Theme(s)</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.query %></td>
        <td><%= question.explanation %></td>
        <td><%= question.level_list %></td>
        <td><%= question.theme_list %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

Dvd/dvd/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<!-- Questions -->
<p>
  <strong>Question</strong>
  <%= @question.query %>
</p>

<p>
  <strong>Indice</strong>
  <%= @question.explanation %>
</p>



<!-- Answers -->
<%= simple_form_for [@quiz, @questions_quiz], remote: true, html: { class: 'form-horizontal', id: 'proposals' } do |f| %>

		<p>Réponse :</p>	

		<% @answers.each do |answer| %>
			<%= f.simple_fields_for :proposals, @questions_quiz.proposals.build do |proposal_builder| %>
 				 
 				<%= proposal_builder.check_box :answer_id, { class: "checkbox" }, answer.id, 0 %>
      	<%= proposal_builder.label :answer_id, answer.title %>
 			  
		  <% end %>
		<% end %>

<% end %>

<% if @question.next(@quiz).present? %>

 <%= link_to 'Question suivante', quiz_question_path(@quiz, @question.next(@quiz)), rel: 'next' %>

 <% else %>

 <%= link_to 'Finish quiz', send_score_path(id:@quiz.id), method:'post', rel: 'next' %>

<% end %>