Dvd/dvd/config/routes.rb
Dvd::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/profile' => 'users#show'

  devise_scope :user do
    authenticated :user do
      root :to => 'quizzes#index', as: :authenticated_root
    end

      
  end  

  resources :quizzes  do
    resources :questions 
    resources :questions_quizzes, only: :update
  end

  resources :questions do
    resources :answers
  end

  get '/a-propos' => 'high_voltage/pages#show', id: 'about', as: :about

  root to: 'high_voltage/pages#show', id: 'home'

  post '/quizzes/:id/send_score' =>  'score#send_score', as: :send_score
  get '/quizzes/:id/score' => 'score#show', as: :score

end

Dvd/dvd/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz, testez vos connaissances ! </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
 

</head>
<body>

<nav class="navbar navbar-default" role="navigation">
 <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Quiz !</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "A propos", about_path %> </li>
      	<% if !user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Connexion <b class="caret"></b></a>
            <ul class="dropdown-menu">
            	<li><%= link_to "J'ai déjà un compte", new_user_session_path %></li>
            	<li><%= link_to "Nouveau compte", new_user_registration_path %></li>
         	  </ul>
          </li>

       	<% else %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.first_name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Nouveau quizz", new_quiz_path %></li>
            <li><%= link_to "Mes quizzes", quizzes_path %></li>
            <li><%= link_to "Mon profil", profile_path %></li>
            <li><%if current_user.admin?%>
              <%= link_to "Nouvelle question", new_question_path %>
              <%end%>
            </li>
            <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>

        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div class="container" id="content">
	<%= yield %>
</div>

    <div id="footer">
      <div class="container">
        
      </div>
    </div>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag :cocoon %>
  <!-- Latest compiled and minified JavaScript -->
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script> 
</body>

</html>