Dvd/dvd/config/routes.rb
Dvd::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/profile' => 'users#show'

  devise_scope :user do
    authenticated :user do
      root :to => 'quizzes#index', as: :authenticated_root
    end

      
  end  

  resources :quizzes  do
    resources :questions 
    resources :questions_quizzes, only: :update
  end

  resources :questions do
    resources :answers
  end

  get '/a-propos' => 'high_voltage/pages#show', id: 'about', as: :about

  root to: 'high_voltage/pages#show', id: 'home'

  post '/quizzes/:id/send_score' =>  'score#send_score', as: :send_score
  get '/quizzes/:id/score' => 'score#show', as: :score

end

Dvd/dvd/app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	
	# Not really an "ownership" relationship
	# proposals refer to answers so this is the relation back to proposals
	# referring to an answer
	has_many :proposals
end

Dvd/dvd/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource param_method: :answer_params

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @answer }
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit()
    end
end

Dvd/dvd/app/helpers/answers_helper.rb
module AnswersHelper
end

Dvd/dvd/app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :good_answer %><br>
    <%= f.text_field :good_answer %>
  </div>
  <div class="field">
    <%= f.label :bad_answer %><br>
    <%= f.text_field :bad_answer %>
  </div>
  <div class="field">
    <%= f.label :bad_answer_2 %><br>
    <%= f.text_field :bad_answer_2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Dvd/dvd/app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

Dvd/dvd/app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

Dvd/dvd/app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>